namespace: ibm
name: qradar
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ibm.qradar.git
documentation: https://github.com/ansible-collection-migration/ibm.qradar/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ibm.qradar
issues: https://github.com/ansible-collection-migration/ibm.qradar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
